# Generated by Django 5.1.8 on 2025-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safar_app', '0003_destination_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='best_time_to_visit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='destination',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='destination',
            name='tagline',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='destination',
            name='tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='weather',
            field=models.TextField(blank=True),
        ),
    ]
