# Generated by Django 5.1.8 on 2025-04-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safar_app', '0005_rename_created_at_review_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safar_app.activity')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safar_app.trip')),
            ],
        ),
    ]
